version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "54322:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./db.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
    db:
        driver: local
